# Generated by Django on 2026-07-22

import datetime
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("accounts", "0006_school_non_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("student", "Student"), ("teacher", "Teacher")],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("expired", "Expired"), ("pending", "Pending")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="schools.school",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_invitation",
                "ordering": ["-created_at"],
            },
        ),
    ]
