# Generated by Django 6.0.7 on 2026-08-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_approve_report_cards',
            field=models.BooleanField(default=False),
        ),
    ]
