# Generated by Django on 2026-07-22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.CharField(max_length=80, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending_verification", "Pending Verification"), ("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "schools_school",
                "ordering": ["name"],
            },
        ),
    ]
