# Generated by Django 6.0.7 on 2026-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_activate_existing_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the school has completed initial setup.'),
        ),
    ]
