# Generated by Django on 2026-07-22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_backfill"),
        ("exams", "0014_term_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("ca", "CA"), ("assignment", "Assignment"), ("practical", "Practical"), ("exam", "Exam"), ("project", "Project")],
                        default="ca",
                        max_length=20,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_components",
                        to="academics.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_components",
                        to="exams.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_components",
                        to="exams.term",
                    ),
                ),
            ],
            options={
                "db_table": "academics_assessment_component",
                "ordering": ["term__display_order", "subject__name", "name"],
                "unique_together": {("subject", "classroom", "term", "name")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField(default=0.0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="academics.assessmentcomponent",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entered_scores",
                        to="accounts.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_scores",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "academics_assessment_score",
                "ordering": ["component__term__display_order", "student__user__last_name"],
                "unique_together": {("component", "student")},
            },
        ),
    ]
