# Generated by Django on 2026-07-22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_assessment"),
        ("exams", "0014_term_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_score", models.FloatField()),
                ("max_score", models.FloatField()),
                ("grade", models.CharField(max_length=8)),
                ("remark", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "academics_grade_scale",
                "ordering": ["-min_score"],
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.FloatField(default=0.0)),
                ("average_score", models.FloatField(default=0.0)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("class_size", models.PositiveIntegerField(default=0)),
                ("teacher_remark", models.TextField(blank=True)),
                ("principal_remark", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted"), ("approved", "Approved")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_report_cards",
                        to="accounts.teacher",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="academics.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="accounts.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="exams.term",
                    ),
                ),
            ],
            options={
                "db_table": "academics_report_card",
                "ordering": ["-created_at"],
                "unique_together": {("student", "classroom", "term")},
            },
        ),
    ]
