# Generated by Django on 2026-07-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_grade_scale_report_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Dee Soar School", max_length=160)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="school/logo/")),
                ("motto", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("principal_name", models.CharField(blank=True, max_length=160)),
                ("principal_signature", models.ImageField(blank=True, null=True, upload_to="school/signatures/")),
                ("vice_principal_name", models.CharField(blank=True, max_length=160)),
                ("vice_principal_signature", models.ImageField(blank=True, null=True, upload_to="school/signatures/")),
                ("primary_color", models.CharField(default="#006c49", max_length=7)),
                ("secondary_color", models.CharField(default="#3c4a42", max_length=7)),
            ],
            options={
                "db_table": "academics_school_profile",
                "verbose_name": "school profile",
                "verbose_name_plural": "school profiles",
            },
        ),
    ]
