# Generated by Django on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("academics", "0006_school_profile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicsession",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_sessions",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcomponent",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_components",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolprofile",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="schools.school",
            ),
        ),
    ]
