# Generated by Django 6.0.7 on 2026-07-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_school_non_nullable'),
        ('accounts', '0007_invitation'),
        ('exams', '0017_school_non_nullable'),
        ('schools', '0002_activate_existing_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'classroom', 'term')},
        ),
        migrations.AddField(
            model_name='reportcard',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='max_score',
            field=models.PositiveIntegerField(default=100, help_text='Maximum attainable score for this component.'),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='name',
            field=models.CharField(help_text='e.g. "CA1", "Exam"', max_length=80),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='score',
            field=models.FloatField(default=0.0, help_text='Score obtained by the student.'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='e.g. "JSS2A"', max_length=80),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='grade',
            field=models.CharField(help_text='e.g. "A", "B2"', max_length=8),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='max_score',
            field=models.FloatField(help_text='Maximum score for this grade (inclusive).'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='min_score',
            field=models.FloatField(help_text='Minimum score for this grade (inclusive).'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='remark',
            field=models.CharField(help_text='e.g. "Excellent", "Good"', max_length=80),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='average_score',
            field=models.FloatField(default=0.0, help_text='Average across subjects.'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='class_size',
            field=models.PositiveIntegerField(default=0, help_text='Snapshot of class size at generation time.'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Computed rank in class.', null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='total_score',
            field=models.FloatField(default=0.0, help_text='Sum of all assessment scores.'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='primary_color',
            field=models.CharField(default='#006c49', help_text='Hex color, e.g. #006c49', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='secondary_color',
            field=models.CharField(default='#3c4a42', help_text='Hex color, e.g. #3c4a42', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together={('subject', 'classroom', 'term', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'grade_level')},
        ),
    ]
