# Generated by Django 6.0.7 on 2026-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_academicsession_unique_together_and_more'),
        ('schools', '0002_activate_existing_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(help_text='e.g. "2025/2026"', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('name', 'school'), name='uq_session_name_per_school'),
        ),
    ]
