# Generated by Django 6.0.7 on 2026-07-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_global_unique_session_name'),
        ('schools', '0003_add_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='schools.school'),
        ),
    ]
