# Generated by Django 6.0.7 on 2026-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_add_school_to_grade_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='grade',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='remark_suggestion',
            field=models.TextField(blank=True),
        ),
    ]
