# Generated by Django 6.0.7 on 2026-07-27 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_grade_and_remark_to_reportcard'),
        ('accounts', '0008_alter_invitation_role_alter_invitation_status_and_more'),
        ('exams', '0019_remove_global_unique_term_name'),
        ('schools', '0003_add_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviouralTrait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('domain', models.CharField(choices=[('affective', 'Affective'), ('psychomotor', 'Psychomotor')], max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavioural_traits', to='schools.school')),
            ],
            options={
                'db_table': 'academics_behavioural_trait',
                'ordering': ['domain', 'display_order', 'name'],
                'unique_together': {('name', 'domain', 'school')},
            },
        ),
        migrations.CreateModel(
            name='BehaviouralRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavioural_ratings', to='academics.classroom')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_behavioural_ratings', to='accounts.teacher')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavioural_ratings', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavioural_ratings', to='accounts.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavioural_ratings', to='exams.term')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='academics.behaviouraltrait')),
            ],
            options={
                'db_table': 'academics_behavioural_rating',
                'ordering': ['term__display_order', 'trait__domain', 'trait__display_order'],
                'unique_together': {('trait', 'student', 'term')},
            },
        ),
    ]
