# Generated by Django 6.0.7 on 2026-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_seed_behavioural_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='school_days_open',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='times_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='times_present',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
