# Generated by Django 6.0.7 on 2026-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_add_teaching_assignment_and_class_teacher'),
        ('accounts', '0008_alter_invitation_role_alter_invitation_status_and_more'),
        ('exams', '0019_remove_global_unique_term_name'),
        ('schools', '0003_add_onboarding_completed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='behaviouralrating',
            index=models.Index(fields=['student', 'classroom', 'term'], name='beh_rating_stu_class_term_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['classroom', 'term', 'status'], name='rpt_classroom_term_status_idx'),
        ),
    ]
