# Generated by Django 6.0.7 on 2026-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_add_report_card_classroom_term_status_index'),
        ('accounts', '0008_alter_invitation_role_alter_invitation_status_and_more'),
        ('exams', '0019_remove_global_unique_term_name'),
        ('schools', '0003_add_onboarding_completed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='behaviouralrating',
            index=models.Index(fields=['student', 'classroom', 'term'], name='beh_rating_student_classroom_term_idx'),
        ),
    ]
