# Generated by Django 6.0.7 on 2026-07-19 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.CharField(blank=True, help_text='Course name, e.g. Algebra I', max_length=160)),
                ('course_code', models.CharField(blank=True, help_text='e.g. MATH-101', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Time limit in minutes')),
                ('total_marks', models.PositiveIntegerField(default=0, help_text='Sum of question marks')),
                ('passing_marks', models.PositiveIntegerField(default=0, help_text='Minimum marks to pass')),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=False)),
                ('show_result', models.BooleanField(default=True, help_text='Reveal score to student after submission')),
                ('allow_review', models.BooleanField(default=True, help_text='Allow student to review answers')),
                ('created_by', models.ForeignKey(help_text='Teacher who authored the exam.', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='accounts.teacher')),
            ],
            options={
                'db_table': 'exams_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on the attempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='accounts.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True / False')], default='single_choice', max_length=20)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Shown after submission if review is allowed')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_question',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Display label, e.g. A, B, C', max_length=8)),
                ('text', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'db_table': 'exams_choice',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('awarded_marks', models.FloatField(default=0.0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Null when the question was left unanswered.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='exams.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exams.question')),
            ],
            options={
                'db_table': 'exams_attempt_answer',
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0, help_text='Marks obtained')),
                ('total_marks', models.FloatField(default=0.0, help_text='Max marks for the exam')),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.attempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='accounts.student')),
            ],
            options={
                'db_table': 'exams_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'created_at'], name='exams_exam_status_73025d_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'student'], name='exams_attem_exam_id_fbec8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['exam', 'passed'], name='exams_resul_exam_id_0f7db2_idx'),
        ),
    ]
