# Generated by Django 6.0.7 on 2026-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the exam was archived.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_group',
            field=models.CharField(blank=True, help_text='e.g. Grade 10', max_length=40),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Shown to students before the exam starts.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the exam is reachable via its public link.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Pass mark as a percentage of total marks (frontend passMark).'),
        ),
        migrations.AddField(
            model_name='exam',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the exam was published.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(blank=True, help_text='e.g. First Term', max_length=40),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['public_token'], name='exams_exam_public__d4793a_idx'),
        ),
    ]
