# Generated by Django 6.0.7 on 2026-07-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_id_alter_teacher_employee_id'),
        ('exams', '0002_exam_archived_at_exam_class_group_exam_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_exam_id_fbec8f_idx',
        ),
        migrations.AddField(
            model_name='attempt',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='class_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='attempt',
            name='client_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form client metadata (e.g. device, timing).'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='attempt',
            name='term',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Optional link to a known student account (public attempts may be anonymous).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'admission_number'], name='exams_attem_exam_id_e9c513_idx'),
        ),
    ]
