# Generated by Django 6.0.7 on 2026-07-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_result_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='_access_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='_public_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
