# Generated by Django 6.0.7 on 2026-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_id_alter_teacher_employee_id'),
        ('exams', '0005_hash_public_and_access_tokens'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'status'], name='exams_attem_student_5c620d_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'status'], name='exams_attem_exam_id_7e3aab_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'percentage'], name='exams_resul_student_9b520f_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['exam', 'student'], name='exams_resul_exam_id_c57e45_idx'),
        ),
    ]
