# Generated by Django 6.0.7 on 2026-07-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_plaintext_tokens'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['public_token_hash'], name='exams_exam_public__c55e71_idx'),
        ),
    ]
