# Generated by Django 6.0.7 on 2026-07-20 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. JSS1', max_length=40, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Sort order')),
            ],
            options={
                'verbose_name': 'grade level',
                'verbose_name_plural': 'grade levels',
                'db_table': 'exams_grade_level',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. First Term', max_length=40, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Sort order')),
            ],
            options={
                'db_table': 'exams_term',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
