# Generated by Django 6.0.7 on 2026-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_seed_grade_levels_and_terms'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE exams_question ADD COLUMN IF NOT EXISTS image varchar(500) NULL",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='question',
                    name='image',
                    field=models.URLField(blank=True, help_text='Cloudinary image URL for the question', max_length=500, null=True),
                ),
            ],
        ),
    ]
