# Generated by Django on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("exams", "0013_add_image_to_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms",
                to="academics.academicsession",
            ),
        ),
    ]
