# Generated by Django on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("exams", "0014_term_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_levels",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="schools.school",
            ),
        ),
    ]
