# Generated by Django 6.0.7 on 2026-07-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_school_non_nullable'),
        ('schools', '0002_activate_existing_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
    ]
