# Generated by Django 6.0.7 on 2026-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_global_unique_session_name'),
        ('exams', '0018_alter_gradelevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text='e.g. First Term', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('name', 'session'), name='uq_term_name_per_session'),
        ),
    ]
